/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gvillena;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
/**
 *
 * @author pc
 */
public class module extends javax.swing.JFrame {
 public String nombre;
    public String pago;
    public String correo;
    public String ciudad;
    public String pais;
    public String marca_celular;
    public String plan;
    public String direccion;
    

      String tarjeta="",caducidad="",clave="",titular="",precio="";
   BufferedWriter bw ;
    PrintWriter pw;
    FileWriter fw;
    File f;
    
    JSONObject obj = new JSONObject();
    JSONArray list = new JSONArray();
   
   
    
    public module() {
        initComponents();
        txtCaducidad.setText("01/24");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     public void Compra(){       
       tarjeta=num_tarjeta.getText();
       caducidad=txtCaducidad.getText();
       clave=contraseña_secreta.getText();
       titular=datospersonales.getText();
       if(num_tarjeta.getText().equals("")||num_tarjeta.getText().length()!=16){
        JOptionPane.showMessageDialog(null, "Ingrese Numero de Tarjeta Correcta");
        num_tarjeta.requestFocus();
       }
       else if(txtCaducidad.getText().equals("")||txtCaducidad.getText().length()!=5){
       JOptionPane.showMessageDialog(null, "Ingrese Fecha de Caducidad Correcta");
       txtCaducidad.requestFocus();
       }
       else if(contraseña_secreta.getText().equals("")){
       JOptionPane.showMessageDialog(null, "Ingrese Clave de Tarjeta");
       contraseña_secreta.requestFocus();
       }
       else if(datospersonales.getText().equals("")){
       JOptionPane.showMessageDialog(null, "Ingrese Nombre de Titular");
       datospersonales.requestFocus();
       }
       else if(identificacion.getText().equals("")){
       JOptionPane.showMessageDialog(null, "Ingrese Su Numero de DNI");
       identificacion.requestFocus();
       }
        else if (telefono_numero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese Su Numero de Celular");
            telefono_numero.requestFocus();
        }
       else if(rbtnTerminos.isSelected()==false){              
              JOptionPane.showMessageDialog(null, "Acepte Terminos y Condiciones de Compra\n");              
       }
       else{
        MainForm m=new MainForm();
        m.setVisible(true);
        m.setLocation(100, 0);
        this.setVisible(false);
       }}
     
       public void RegistrarVentaJson()throws IOException{
      
      f= new File("D:\\ResgistroVentas.txt");
      obj.put("VENDEDOR", "Victoria Bobadilla Alvarado");
      obj.put("TIENDA", "TELEFONIA PERU SAC");
      JSONObject objc = new JSONObject();
       objc.put("Nombre: ", nombre);              
      objc.put("Email: ", correo);
      objc.put("Ciudad: ", ciudad);
      objc.put("Pais: ", pais);
      objc.put("Marca de Celular: ", marca_celular);
      objc.put("Plan PostPago: ",plan);      
      objc.put("Pago: ", pago);
      obj.put("FACTURA",objc );      
      fw= new FileWriter("D:\\ResgistroVentas.txt");
      fw.write(obj.toJSONString());
      fw.flush();
      fw.close();
  }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        lbl_modulo = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_dni = new javax.swing.JLabel();
        lbl_credito = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JLabel();
        lbl_ciudad = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        listado = new javax.swing.JComboBox<>();
        datospersonales = new javax.swing.JTextField();
        identificacion = new javax.swing.JTextField();
        ubicacion = new javax.swing.JTextField();
        telefono_numero = new javax.swing.JTextField();
        lbl_contraseña = new javax.swing.JLabel();
        contraseña_secreta = new javax.swing.JPasswordField();
        num_tarjeta = new javax.swing.JTextField();
        lbl_aceptamos = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        lblimagen = new javax.swing.JLabel();
        txtCaducidad = new javax.swing.JTextField();
        rbtnTerminos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_modulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 36)); // NOI18N
        lbl_modulo.setForeground(new java.awt.Color(0, 0, 204));
        lbl_modulo.setText("MODULO DE PAGO");
        lbl_modulo.setMaximumSize(new java.awt.Dimension(150, 14));
        lbl_modulo.setMinimumSize(new java.awt.Dimension(150, 14));

        lbl_nombre.setText("NOMBRE DEL CLIENTE");

        lbl_dni.setText("DNI");

        lbl_credito.setText("N° DE TARJETA DE CREDITO");

        lbl_fecha.setText("FECHA DE CAUDOCIDAD");

        lbl_direccion.setText("DIRRECCION");

        lbl_telefono.setText("Nº TELEFONICO");

        lbl_ciudad.setText("CIUDAD");

        aceptar.setText("ACEPTAR");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        listado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoActionPerformed(evt);
            }
        });

        datospersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datospersonalesActionPerformed(evt);
            }
        });

        ubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubicacionActionPerformed(evt);
            }
        });

        telefono_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono_numeroActionPerformed(evt);
            }
        });

        lbl_contraseña.setText("CONTRASEÑA");

        contraseña_secreta.setText("jPasswordField1");

        num_tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_tarjetaActionPerformed(evt);
            }
        });

        lbl_aceptamos.setText("ACEPTAMOS:");

        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        lblimagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\tarjeta.jpg")); // NOI18N
        lblimagen.setText("jLabel1");

        txtCaducidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaducidadActionPerformed(evt);
            }
        });

        rbtnTerminos.setText("Acepto los terminos y condicines de la Compra.");
        rbtnTerminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTerminosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_dni)
                                    .addComponent(lbl_nombre)
                                    .addComponent(lbl_contraseña)
                                    .addComponent(lbl_direccion)
                                    .addComponent(lbl_telefono)
                                    .addComponent(lbl_ciudad)
                                    .addComponent(lbl_credito))
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(listado, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(contraseña_secreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(num_tarjeta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                                .addComponent(telefono_numero, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(identificacion, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(datospersonales, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_aceptamos)
                                            .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_fecha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(rbtnTerminos)
                                .addGap(18, 18, 18)
                                .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lbl_modulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombre)
                            .addComponent(datospersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_dni))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_credito, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contraseña_secreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_contraseña))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_direccion)
                            .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_telefono)
                            .addComponent(telefono_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_modulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(lbl_aceptamos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblimagen)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ciudad)
                    .addComponent(listado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cancelar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnTerminos)
                        .addComponent(aceptar)))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num_tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_tarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_tarjetaActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        Compra();
          try {
               RegistrarVentaJson(); 
              JOptionPane.showMessageDialog(null, "COMPRA CON EXITO");
          } catch (IOException ex) {
              JOptionPane.showMessageDialog(null, "ERROR AL CREAR FICHERO DE VENTA\n"+ex);
              }

        
    }//GEN-LAST:event_aceptarActionPerformed

    private void listadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoActionPerformed

    private void datospersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datospersonalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datospersonalesActionPerformed

    private void ubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubicacionActionPerformed

    private void telefono_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefono_numeroActionPerformed

    private void txtCaducidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaducidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaducidadActionPerformed

    private void rbtnTerminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTerminosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTerminosActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
         MainForm m = new MainForm();
        m.setVisible(true); 
        m.setLocation(100, 0);
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed
 public void AbrirCarpeta()
        {

        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new module().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JPasswordField contraseña_secreta;
    private javax.swing.JTextField datospersonales;
    private javax.swing.JTextField identificacion;
    private javax.swing.JLabel lbl_aceptamos;
    private javax.swing.JLabel lbl_ciudad;
    private javax.swing.JLabel lbl_contraseña;
    private javax.swing.JLabel lbl_credito;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_dni;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_modulo;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JComboBox<String> listado;
    private javax.swing.JTextField num_tarjeta;
    private javax.swing.JRadioButton rbtnTerminos;
    private javax.swing.JTextField telefono_numero;
    private java.awt.TextArea textArea1;
    private javax.swing.JTextField txtCaducidad;
    private javax.swing.JTextField ubicacion;
    // End of variables declaration//GEN-END:variables
}
